#!/usr/bin/env bash
set -euo pipefail

readonly project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

mock_server_pid="-1"

trap 'kill ${mock_server_pid}' EXIT

function build() {
    "$project_dir/gradlew" --project-dir "$project_dir" build
}

# $1 — port
# $2 - data directory
function run_mock_bintray_server() {
    java \
        -jar "$project_dir/mock-bintray/build/libs/mock-bintray-all.jar" \
        --port "$1" \
        --data-dir "$2" \
        &
    mock_server_pid="$!"
}

function run_bintray_backuper() {
    java \
        -jar "$project_dir/bintray-backuper/build/libs/bintray-backuper-all.jar" \
        --api-endpoint "http://127.0.0.1:8080" \
        --downloads-endpoint "http://127.0.0.1:8080" \
        --subject "test-org" \
        --download-dir "$project_dir/integration-test/downloads"
}

function main() {
    build
    run_mock_bintray_server "8080" "$project_dir/integration-test/test-data-1"
    run_bintray_backuper
}

main
